const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const base=__dirname+'/';let count=0;const check=(name,fn)=>{fn();count++;console.log('OK '+name)};
const ctx={console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(base+'core.js','utf8'),ctx);const C=ctx.LudariaCore;
check('14 runas, 49 puntos, 570 XP, cuatro fragmentos',()=>{const p=C.defP('Prueba','Kira');Object.keys(C.CM).forEach(c=>C.redeem(p,c));assert.equal(p.points,49);assert.equal(p.xp,570);assert.equal(p.level,6);assert.equal(C.fragments(p).length,4);assert.equal(C.missionDone(p),12);assert(p.achs.includes('orbe_restaurado'));});
check('código duplicado no otorga nada',()=>{const p=C.defP('Prueba','Kael');C.redeem(p,'eco101');assert.throws(()=>C.redeem(p,'ECO101'));assert.equal(p.points,3);});
check('compra, XP intacta, cap 10 y saldo insuficiente',()=>{const p=C.defP('Prueba','Kael');C.redeem(p,'ECO101');p.pending.sabiduria=2;p.pending.camaraderia=1;assert.equal(C.confirmSpend(p),3);assert.equal(p.xp,30);assert.equal(p.points,0);assert.equal(p.skills.sabiduria,3);assert.equal(C.allocate(p,'creacion',1),false);assert.equal(C.unlock(p,'sabiduria',1),true);assert.equal(C.unlock(p,'sabiduria',1),false);assert.equal(C.unlock(p,'sabiduria',2),false);p.points=45;C.SKS.forEach(s=>p.pending[s.key]=10-p.skills[s.key]);C.confirmSpend(p);assert.equal(C.allocate(p,'sabiduria',1),false);});
check('importación antigua conserva alias y progreso',()=>{const p=C.normalize({name:'Antigua',class:'Kira',skills:{narrativa:3,diseno:5,creatividad:2,estrategia:4,motivacion:6},points:7,xp:140,codes:['AXR314'],nodes:['narrativa_1'],achs:[]});assert.equal(p.skills.sabiduria,3);assert.equal(p.skills.camaraderia,6);assert.equal(p.points,7);assert.equal(p.level,3);assert(p.nodes.includes('sabiduria_1'));assert(p.missions.includes('AXR314'));});
class Sheet{constructor(){this.rows=[];}getLastRow(){return this.rows.length}appendRow(r){this.rows.push(structuredClone(r));return this}getDataRange(){return {getValues:()=>structuredClone(this.rows)}}getRange(row,col,n=1,m=1){return {setValues:v=>{v.forEach((r,i)=>{this.rows[row-1+i]??=[];r.forEach((x,j)=>this.rows[row-1+i][col-1+j]=x)});return this},getValues:()=>this.rows.slice(row-1,row-1+n).map(r=>r.slice(col-1,col-1+m)),setValue:v=>{this.rows[row-1][col-1]=v},setBackground:()=>({setFontColor:()=>({setFontWeight:()=>{}})})}}setFrozenRows(){}autoResizeColumns(){}}
const sheets={},ss={getId:()=> 'private-test-sheet',getSheetByName:n=>sheets[n],insertSheet:n=>(sheets[n]=new Sheet())},props={};
Object.assign(ctx,{SpreadsheetApp:{getActiveSpreadsheet:()=>ss,openById:()=>ss},PropertiesService:{getScriptProperties:()=>({setProperty:(k,v)=>props[k]=v,getProperty:k=>props[k]})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(alg,s)=>[...crypto.createHash('sha256').update(s).digest()]},LockService:{getScriptLock:()=>({tryLock:()=>true,waitLock:()=>{},releaseLock:()=>{}})}});
vm.runInContext(fs.readFileSync(base+'apps-script/Code.gs','utf8'),ctx);ctx.setupForja_();
const access={id:crypto.randomUUID(),key:crypto.randomUUID()+crypto.randomUUID()};let request=()=>crypto.randomUUID();const api=(action,data={},id=request(),a=access)=>ctx.forjaApi({action,data,access:a,requestId:id});
check('servidor crea y autentica sin exponer otras fichas',()=>{assert(api('crear',{name:'Cuenta prueba',class:'Kira'}).ok);assert.equal(api('cargar').profile.points,0);assert.equal(api('cargar',{},request(),{...access,key:'a'.repeat(64)}).ok,false);assert.equal(api('cargar',{},request(),{...access,id:crypto.randomUUID()}).ok,false);});
check('reintento idempotente y doble runa bloqueada',()=>{const id=request();assert(api('runa',{code:'ECO101'},id).ok);assert(api('runa',{code:'ECO101'},id).ok);assert.equal(api('cargar').profile.points,3);assert.equal(api('runa',{code:'ECO101'}).ok,false);});
check('cantidades manipuladas y saldo ficticio rechazados',()=>{for(const q of [{sabiduria:-1},{sabiduria:NaN},{sabiduria:1.5},{sabiduria:10}]){assert.equal(api('compra',{quantities:q,points:9999}).ok,false)}const q=Object.fromEntries(C.SKS.map(s=>[s.key,0]));q.sabiduria=4;assert.equal(api('compra',{quantities:q}).ok,false);assert.equal(api('cargar').profile.points,3);});
check('compra central una sola vez, XP y talento correctos',()=>{const q=Object.fromEntries(C.SKS.map(s=>[s.key,0]));q.sabiduria=2;q.camaraderia=1;const id=request();assert(api('compra',{quantities:q},id).ok);assert(api('compra',{quantities:q},id).ok);const p=api('cargar').profile;assert.equal(p.points,0);assert.equal(p.xp,30);assert.equal(p.skills.sabiduria,3);assert.equal(sheets.Movimientos.rows.filter(r=>r[3]==='compra').length,1);assert(api('talento',{key:'sabiduria',tier:1}).ok);assert.equal(api('talento',{key:'sabiduria',tier:2}).ok,false);});
check('migración requiere revisión y no acredita puntos',()=>{const p=C.defP('Antiguo','Kael');p.points=999;assert(api('migracion',{profile:p}).ok);assert.equal(api('cargar').profile.points,0);assert.equal(sheets.Migraciones.rows[1][4],'Pendiente');});
check('solo API y doGet son funciones públicas',()=>{const names=[...fs.readFileSync(base+'apps-script/Code.gs','utf8').matchAll(/function\s+(\w+)\(/g)].map(x=>x[1]);assert.deepEqual(names.filter(n=>!n.endsWith('_')).sort(),['doGet','forjaApi']);});
console.log('PASS '+count+' grupos de pruebas; sin despliegue Google real.');

