'use strict';
(() => {
const KEY='gamiaula_claro_debate_v1',C=window.CLARO_CONTENT,CONFIG=window.CLARO_CONFIG;
const titles=['El Claro del Debate','El encargo de Théol','Antes de abrir el archivo','Las lecturas del claro','Una tendencia favorable','La huella y el aprendizaje','Los adornos del juego','Distintas miradas','El círculo de argumentos','El hilo de una buena defensa','La síntesis del mentor','El Fragmento I del Orbe'];
const seals=['Alcance','Inferencia','Argumento'];
const minutes=[3,5,8,10,7,7,7,7,12,8,10,6];
const fieldNames={initial:'Una afirmación que nos hizo dudar',argument:'Nuestra afirmación revisada',evidence:'La evidencia que la sostiene',limit:'Un límite o explicación alternativa',decision:'Una decisión para el aula',peer:'Una pregunta de otro equipo y nuestro ajuste',synthesis:'Una idea que mantenemos, una que matizamos y una pregunta pendiente',exit:'Mi aprendizaje del módulo y mi próximo paso'};
const defaults=()=>({version:1,page:0,visited:[0],seals:['pending','pending','pending'],hints:[0,0,0],read:[],before:{},after:{},revealed:[],scope:null,classify:{},order:[],fields:{},chosenStatement:'a',timer:{left:600,running:false},fragment:false,closingRecorded:false});
let state=defaults(),storageOK=true,feedback={},opener=null,toastTimer,exportUrl=null;
try{
  const s=JSON.parse(localStorage.getItem(KEY)||'null');
  if(s&&s.version===1){
    state={...state,...s};
    if(!Number.isInteger(state.page)||state.page<0||state.page>=titles.length)state.page=0;
    for(const k of ['visited','read','revealed','order'])if(!Array.isArray(state[k]))state[k]=[];
    for(const k of ['before','after','classify','fields'])if(!state[k]||typeof state[k]!=='object'||Array.isArray(state[k]))state[k]={};
    state.seals=Array.isArray(state.seals)&&state.seals.length===3?state.seals.map(x=>['solved','assisted'].includes(x)?x:'pending'):defaults().seals;
    if(!Array.isArray(state.hints)||state.hints.length!==3)state.hints=[0,0,0];
    if(!state.timer||!Number.isFinite(state.timer.left))state.timer=defaults().timer;
    state.timer.left=Math.min(600,Math.max(0,Math.floor(state.timer.left)));state.timer.running=false;
    if(!C.statements.some(x=>x.id===state.chosenStatement))state.chosenStatement='a';
    state.order=state.order.filter((x,n,a)=>C.argumentSteps.some(y=>y.id===x)&&a.indexOf(x)===n);
  }
}catch(e){storageOK=false;}
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){storageOK=false;}};
const status=x=>x==='solved'?'Resuelto':x==='assisted'?'Apertura acompañada':'Por resolver';
const voteLabel=x=>({support:'La sostengo',question:'La cuestiono',unsure:'Necesito evidencia',nuance:'La matizo'}[x]||'Sin registrar');
const action=(id,label,extra='',secondary=false)=>`<button class="button ${secondary?'secondary':''}" data-action="${id}" ${extra}>${label}</button>`;
const heading=(n,title,description='',time=null)=>`<div class="section-title"><div><span class="eyebrow">${n}</span><h2>${title}</h2></div>${time?`<span class="time-label">${time} min · en equipos</span>`:''}</div>${description?`<p class="lead">${description}</p>`:''}`;
const field=(id,rows=3,placeholder='Escribe con tus palabras…')=>`<label class="field" for="field-${id}">${fieldNames[id]}<textarea id="field-${id}" data-field="${id}" rows="${rows}" maxlength="6000" placeholder="${placeholder}">${esc(state.fields[id])}</textarea></label>`;
const fb=k=>feedback[k]?`<div class="feedback ${feedback[k].kind||''}" role="status">${feedback[k].text}</div>`:'';
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
function setFeedback(key,text,kind=''){feedback[key]={text,kind};render(false);}
function choice(actionName,value,label,selected,extra=''){
  return `<button class="choice ${selected?'selected':''}" data-action="${actionName}" data-option="${value}" ${extra} aria-pressed="${Boolean(selected)}"><span class="choice-mark" aria-hidden="true">${selected?'✓':'○'}</span><span>${label}</span></button>`;
}
function voteButtons(id,phase){
  const choices=phase==='before'?[['support','La sostengo'],['question','La cuestiono'],['unsure','Necesito evidencia']]:[['support','La sostengo'],['question','La cuestiono'],['nuance','La matizo']];
  if(phase==='before'&&state.revealed.includes(id))return `<p class="vote-record">Postura inicial: <strong>${voteLabel(state.before[id])}</strong><span class="note">Se conserva como registro anterior a la lectura.</span></p>`;
  return `<div class="vote-options" role="group" aria-label="${phase==='before'?'Postura inicial':'Postura después de la lectura'} sobre la afirmación ${id.toUpperCase()}">${choices.map(([v,l])=>choice('vote',v,l,state[phase][id]===v,`data-statement="${id}" data-phase="${phase}"`)).join('')}</div>`;
}
function lockGlyph(open){return `<div class="lock-glyph" aria-hidden="true"><svg viewBox="0 0 48 48"><rect x="10" y="21" width="28" height="22" rx="3"/><path d="${open?'M17 21v-7a8 8 0 0 1 15-4':'M16 21v-7a8 8 0 0 1 16 0v7'}"/><circle cx="24" cy="30" r="2"/><path d="M24 32v5"/></svg></div>`;}
function lockPanel(i){const open=state.seals[i]!=='pending';return `<aside class="lock-panel ${open?'open':''}">${lockGlyph(open)}<div class="lock-meta"><span class="eyebrow">CANDADO ${['I','II','III'][i]}</span><h3>${seals[i]}</h3></div><p>${open?status(state.seals[i]):['Distingue una tendencia de una garantía.','Separa el registro de la interpretación.','Conecta una afirmación con una decisión revisable.'][i]}</p>${action(open?'reward':'challenge',open?'Consultar lo revelado':'Explorar el candado',`data-seal="${i}"`,true)}</aside>`;}
function sourceBody(key){const s=C.sources[key];return `<span class="pill">${s.kind}</span><p style="margin-top:22px">${s.summary}</p><h3>Hasta dónde podemos afirmar</h3><p>${s.limit}</p>${s.metrics?metricTable():''}<div class="source-line"><a href="${s.url}" target="_blank" rel="noopener noreferrer">Consultar publicación original</a></div><p class="note">${s.citation}</p>`;}
function metricTable(){return `<div class="table-scroll"><table class="comparison"><caption>Resultados de Sailer y Homner (2020)</caption><thead><tr><th>Resultado</th><th>g</th><th>IC del 95 %</th><th>Estudios</th><th>Participantes</th></tr></thead><tbody>${C.sources.sailer.metrics.map(x=>`<tr><th>${x.label}</th><td>${x.g}</td><td>${x.interval}</td><td>${x.studies}</td><td>${x.participants.toLocaleString('es-CL')}</td></tr>`).join('')}</tbody></table></div><p class="note">g expresa una diferencia estandarizada entre grupos. No representa un porcentaje de mejora. Las categorías reúnen conjuntos de estudios que pueden solaparse.</p>`;}
function roundPage(index){
  const s=C.statements[index],read=state.revealed.includes(s.id),source=C.sources[s.source];
  return `<section class="scene"><div class="scene-content wide">${heading('RONDA '+String(index+1).padStart(2,'0')+' · CONTRASTAR CON EVIDENCIA',s.title,'Lee la afirmación, revisa la lectura y decide qué conservar o matizar.',7)}<div class="split debate-split"><div><blockquote class="claim">«${s.claim}»</blockquote><div class="round-initial"><span class="mini-label">PRIMERA POSTURA</span>${voteButtons(s.id,'before')}</div>${read?`<div class="reading-reveal"><span class="eyebrow">LA LECTURA REVELADA</span><p>${source.summary}</p><div class="source-line">${action('source','Abrir lectura y límites',`data-source="${s.source}"`,true)}</div></div><div class="round-after"><span class="mini-label">SEGUNDA POSTURA</span>${voteButtons(s.id,'after')}</div><p class="note">${state.after[s.id]?`Tu postura quedó registrada: ${voteLabel(state.after[s.id])}. Mantener o cambiar una idea exige justificarla.`:'Esta postura es una decisión argumentativa; no recibe una nota automática.'}</p><details><summary>Una pregunta para tu argumento</summary><p class="question-note">${s.question}</p><p class="note">${s.feedback}</p></details>`:`<div class="sealed-reading"><span class="mini-label">UNA LECTURA ENTRE LA BRUMA</span><p>${s.lens}</p>${action('reveal','Revelar la evidencia',`data-statement="${s.id}"`)}<p class="note">Puedes consultar las lecturas aunque todavía no hayas registrado una postura.</p></div>`}</div>${index===0?lockPanel(0):index===2?lockPanel(1):`<aside class="side-note">${index===1?'¿Qué se midió realmente?<br>¿Qué falta observar?':'Una decisión se revisa también<br>con quienes la viven.'}<div class="header-rule"></div><p class="note">${s.lens}</p>${action(index===1?'metrics':'notebook',index===1?'Examinar los resultados':'Anotar una pregunta','',true)}</aside>`}</div></div></section>`;
}
function orderActivity(){
  return `<div class="order-instructions"><p class="note">Selecciona las tarjetas para construir una secuencia de argumentación. Puedes deshacer el último paso.</p></div><ol class="argument-chain" aria-label="Secuencia construida">${state.order.length?state.order.map((id,n)=>`<li><span>${String(n+1).padStart(2,'0')}</span>${C.argumentSteps.find(x=>x.id===id).label}</li>`).join(''):'<li class="empty-chain">Aquí aparecerá el hilo de tu defensa.</li>'}</ol><div class="order-options">${[C.argumentSteps[2],C.argumentSteps[0],C.argumentSteps[3],C.argumentSteps[1]].map(x=>`<button class="choice ${state.order.includes(x.id)?'used':''}" data-action="order-add" data-option="${x.id}" ${state.order.includes(x.id)?'disabled':''}><span class="choice-mark" aria-hidden="true">+</span><span>${x.label}</span></button>`).join('')}</div><div class="actions">${action('check-lock','Abrir el candado', 'data-seal="2"')}<button class="text-button" data-action="order-undo" ${!state.order.length?'disabled':''}>Deshacer último paso</button><button class="text-button" data-action="order-reset">Recomenzar la secuencia</button></div>${fb('lock2')}<div class="actions"><button class="text-button" data-action="hint" data-seal="2">Pedir una pista</button><button class="text-button" data-action="assist" data-seal="2">Resolver con el facilitador</button></div>`;
}
function orbSVG(){return `<svg class="orb-svg ${state.fragment?'restored':''}" viewBox="0 0 320 320" role="img" aria-label="${state.fragment?'Fragmento I revelado; quedan tres fragmentos del Orbe':'Orbe con cuatro fragmentos; el primer fragmento espera el cierre del módulo'}"><defs><radialGradient id="fragment-light" cx=".8" cy=".25" r=".95"><stop offset="0" stop-color="#d1ffc9"/><stop offset=".48" stop-color="#72c88d"/><stop offset="1" stop-color="#163e2c"/></radialGradient></defs><circle cx="160" cy="160" r="137" fill="none" stroke="#c9a66b" stroke-width="1"/><circle cx="160" cy="160" r="125" fill="#081b1399" stroke="#c9a66b66" stroke-width="1"/><path class="first-fragment" d="M156 39A121 121 0 0 0 39 156H142V142H156Z" fill="url(#fragment-light)" stroke="#d9e9b4" stroke-width="1.5"/><path d="M164 39A121 121 0 0 1 281 156H178V142H164Z M281 164A121 121 0 0 1 164 281V178H178V164Z M156 281A121 121 0 0 1 39 164H142V178H156Z" fill="#0d281e55" stroke="#9ab68b55" stroke-width="1" stroke-dasharray="4 7"/><circle cx="160" cy="160" r="13" fill="none" stroke="#c9a66b99"/><text x="100" y="112" text-anchor="middle" fill="#f2ebdd" font-size="32" font-family="Georgia,serif">I</text></svg>`;}
const pages=[
 ()=>`<section class="scene"><div class="cover-content"><span class="eyebrow">BOSQUE DE LOS CONCEPTOS · MISIÓN SECUNDARIA 2</span><h1 class="cover-title">El Claro<br>del <span>Debate</span></h1><p class="lead">Las Brumas del Olvido confunden certezas y promesas. Toma postura. Abre las lecturas. Defiende una idea que pueda sostenerse.</p><div class="actions">${action('begin','Entrar en el claro')}<button class="text-button" data-action="map">Explorar el recorrido</button></div><div class="cover-meta"><span class="small-line"></span><span>Archivista Théol</span><span>Sabiduría</span></div>${state.visited.length>1?'<p class="note">Tu recorrido está guardado en este navegador.</p>':''}</div><span class="media-note">LUDARIA · UNA PREGUNTA ABRE EL CAMINO</span></section>`,
 ()=>`<section class="scene"><div class="scene-content wide">${heading('EL ENCARGO DEL ARCHIVISTA','Una buena defensa<br>deja espacio a la duda.','Hoy contrastamos mitos y evidencia. El módulo termina con el Fragmento I del Orbe del Saber.',5)}<div class="mentor">«No gana quien habla más fuerte. Avanzamos cuando una afirmación encuentra evidencia y reconoce hasta dónde puede llegar».<small>ARCHIVISTA THÉOL</small></div><div class="three-column">${[['I','Alcance','¿Estamos viendo una tendencia o prometiendo una garantía?'],['II','Inferencia','¿Describimos un registro o proponemos una explicación?'],['III','Argumento','¿Conectamos evidencia, límite y una decisión revisable?']].map(x=>`<div class="panel"><span class="num">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div><p class="note">Primera postura → lecturas → segunda postura → debate → síntesis. Pistas y reintentos sin penalización. Las posturas se argumentan; los candados son práctica local.</p></div></section>`,
 ()=>`<section class="scene"><div class="scene-content wide">${heading('ANTES DE ABRIR EL ARCHIVO','¿Dónde se sitúa<br>tu primera mirada?','Conversen en el equipo y registren una postura por afirmación. No hay corrección automática de esta votación.',8)}<div class="position-grid">${C.statements.map((s,n)=>`<article class="position-card"><span class="mini-label">AFIRMACIÓN ${String(n+1).padStart(2,'0')}</span><h3>${s.claim}</h3>${voteButtons(s.id,'before')}</article>`).join('')}</div><div class="initial-note">${field('initial',2,'¿Qué afirmación produjo más dudas o desacuerdos?')}</div><p class="note">Este registro pertenece al equipo que usa este navegador; no es una votación del grupo completo.</p></div></section>`,
 ()=>`<section class="scene"><div class="scene-content wide">${heading('LAS LECTURAS DEL CLARO','Tres fuentes.<br>Preguntas más precisas.','Explora tres síntesis de investigación y anota qué permiten afirmar.',10)}<div class="three-column source-grid">${Object.entries(C.sources).map(([k,s],n)=>`<button class="panel source-card ${state.read.includes(k)?'seen':''}" data-action="source" data-source="${k}"><span class="num">0${n+1}</span><span class="mini-label">${s.kind}</span><h3>${s.title}</h3><p>${s.short}</p><span class="source-state">${state.read.includes(k)?'Lectura explorada':'Abrir lectura y límites'}</span></button>`).join('')}</div><div class="split"><div class="side-note">¿Qué se comparó?<br>¿Qué resultado se midió?<br>¿Dónde termina la conclusión?</div><div><p class="note">Un metaanálisis combina estimaciones de varios estudios. Una revisión sistemática organiza investigaciones seleccionadas con criterios explícitos. Lee también los límites.</p><div class="actions">${action('metrics','Examinar las estimaciones','',true)}${action('notebook','Anotar una evidencia','',true)}</div></div></div></div></section>`,
 ()=>roundPage(0),()=>roundPage(1),()=>roundPage(2),()=>roundPage(3),
 ()=>`<section class="scene"><div class="scene-content wide">${heading('EL CÍRCULO DE ARGUMENTOS','Escucha una objeción.<br>Haz más precisa tu idea.','Cada equipo defiende una afirmación, recibe preguntas y revisa su argumento.',12)}<div class="split workshop-split"><div><label class="field" for="chosen-statement">Afirmación para defender<select id="chosen-statement" data-group="statement">${C.statements.map((s,n)=>`<option value="${s.id}" ${state.chosenStatement===s.id?'selected':''}>${n+1}. ${s.title}</option>`).join('')}</select></label><p class="selected-claim">${C.statements.find(s=>s.id===state.chosenStatement).claim}</p><div class="work-grid">${field('argument',2)}${field('evidence',2)}${field('limit',2)}${field('decision',2)}</div>${field('peer',2)}<div class="actions">${action('review','Abrir pauta de argumentación','',true)}</div></div><aside><div class="timer-box"><span class="eyebrow">CONVERSACIÓN ENTRE EQUIPOS</span><div id="timer" class="timer">${timerText()}</div><div class="actions">${action('timer-toggle',state.timer.running?'Pausar':'Iniciar','',true)}<button class="text-button" data-action="timer-reset">Reiniciar</button></div><p class="note">Diez minutos orientativos. Puedes continuar cuando termine.</p></div><div class="discussion-roles"><p><strong>Presenta.</strong> Afirmación, evidencia y límite.</p><p><strong>Pregunta.</strong> ¿Qué sostiene esa conclusión? ¿Qué falta saber?</p><p><strong>Ajusta.</strong> Propón una decisión que puedas revisar.</p></div></aside></div></div></section>`,
 ()=>`<section class="scene"><div class="scene-content wide">${heading('TERCER UMBRAL · SÍNTESIS FORMATIVA','El hilo de<br>una buena defensa.','Ordena esta pauta para conectar el argumento con una acción para tu aula.',8)}<div class="split challenge-split"><div>${orderActivity()}<p class="note">Esta secuencia es una pauta didáctica de la misión. Abrir el sello no califica tu texto ni exige cambiar de postura.</p></div>${lockPanel(2)}</div></div></section>`,
 ()=>`<section class="scene"><div class="scene-content wide">${heading('LA SÍNTESIS DEL MENTOR','De una certeza rápida<br>a una decisión revisable.','Pongan en común los argumentos. Théol ayuda a distinguir acuerdos, matices y preguntas pendientes.',10)}<div class="table-scroll"><table class="comparison vote-comparison"><caption>Posturas de este equipo en este navegador</caption><thead><tr><th>Afirmación</th><th>Antes de leer</th><th>Después de leer</th></tr></thead><tbody>${C.statements.map((s,n)=>`<tr><th>${n+1}. ${s.title}</th><td>${voteLabel(state.before[s.id])}</td><td>${voteLabel(state.after[s.id])}</td></tr>`).join('')}</tbody></table></div><div class="three-column synthesis-cards"><div class="panel"><h3>Qué podemos sostener</h3><p>Una afirmación precisa, con evidencia pertinente y alcance explícito.</p></div><div class="panel"><h3>Qué debemos revisar</h3><p>La relación entre la propuesta, el objetivo, el contexto y lo que observamos.</p></div><div class="panel"><h3>Qué sigue abierto</h3><p>Las preguntas que esta lectura no resuelve y las que probaríamos en nuestra aula.</p></div></div><div style="margin-top:24px">${field('synthesis',3)}</div><div class="actions">${action('review','Revisar nuestra síntesis','',true)}${action('download','Preparar la bitácora','',true)}</div></div></section>`,
 ()=>`<section class="scene"><div class="scene-content wide">${heading('CIERRE DEL MÓDULO 1','Una primera luz<br>regresa al Orbe.','El Bosque de los Conceptos deja una idea: reconocer, analizar y argumentar para decidir.',6)}<div class="split closing-split"><div><div class="final-seals">${seals.map((s,i)=>`<div class="final-seal ${state.seals[i]}"><strong>${s}</strong><small>${status(state.seals[i])}</small></div>`).join('')}</div><div style="margin-top:24px">${field('exit',2,'¿Qué idea revisaste y qué te propones hacer después?')}</div><div class="actions">${action('save-closing','Guardar mi cierre')}${action('download','Preparar la bitácora','',true)}</div>${state.closingRecorded?'<p class="note"><span class="pill">Reflexión registrada</span> Revísala con el facilitador.</p>':''}<div class="closing-form">${validFormUrl()?`<a class="button secondary" href="${esc(CONFIG.closingFormUrl)}" target="_blank" rel="noopener noreferrer">Abrir formulario de cierre del módulo</a>`:'<p class="note">Completa el formulario de cierre del módulo que compartirá el facilitador.</p>'}</div><p class="note">Después de la puesta en común, Théol conduce el cierre narrativo de la sesión.</p><div class="actions">${action(state.fragment?'fragment-info':'fragment-ask',state.fragment?'Volver a contemplar el fragmento':'Revelar el Fragmento I')}</div><p class="note">Próximo destino: <strong>Las Vetas del Diseño</strong> · Cantera de los Elementos.</p></div><aside class="orb-panel">${orbSVG()}<span class="eyebrow">FRAGMENTO I · BOSQUE DE LOS CONCEPTOS</span><p>${state.fragment?'El primer fragmento ha sido revelado en el cierre de esta sesión. Tres fragmentos esperan más adelante.':'El primer fragmento espera la síntesis compartida del módulo.'}</p><span class="note">Los sellos y este cierre se registran aquí; no actualizan la Forja ni el Libro de Stats.</span></aside></div></div></section>`
];
function validFormUrl(){try{const u=new URL(CONFIG.closingFormUrl);return ['https:','http:'].includes(u.protocol);}catch(e){return false;}}
function timerText(){return String(Math.floor(state.timer.left/60)).padStart(2,'0')+':'+String(state.timer.left%60).padStart(2,'0');}
function render(focus=false){
  document.body.classList.toggle('is-cover',state.page===0);
  $('world').classList.toggle('archive',[3,4,5,6,7,8,9,10].includes(state.page));
  $('stage').innerHTML=pages[state.page]();
  $('seal-status').innerHTML=state.seals.map((s,i)=>`<button class="seal-dot ${s}" data-action="seal-info" data-seal="${i}" aria-label="${seals[i]}: ${status(s)}" title="${seals[i]}: ${status(s)}">${['I','II','III'][i]}</button>`).join('');
  $('page-number').textContent=String(state.page+1).padStart(2,'0')+' / '+titles.length;
  $('route-dots').innerHTML=titles.map((t,i)=>`<button class="route-dot ${state.visited.includes(i)?'visited':''} ${i===state.page?'current':''}" data-action="go" data-page="${i}" title="${i+1}. ${t}" aria-label="${i+1}. ${t}" ${i===state.page?'aria-current="step"':''}></button>`).join('');
  $('previous').disabled=state.page===0;$('next').disabled=state.page===titles.length-1;$('next-label').textContent=state.page===0?'Entrar':'Siguiente';
  if(focus){$('stage').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
}
function go(page){if(!Number.isInteger(page)||page<0||page>=titles.length)return;closeModal();state.page=page;if(!state.visited.includes(page))state.visited.push(page);save();try{history.replaceState(null,'','#pantalla-'+(page+1));}catch(e){}render(true);}
function showModal(title,body){
  if(!$('modal').open){opener=document.activeElement;if(!opener||opener===document.body||opener===document.documentElement)opener=document.querySelector('#stage [data-action]');}
  $('modal-body').innerHTML=`<h2 id="modal-title">${title}</h2>${body}`;
  if(!$('modal').open)$('modal').showModal();
  $('modal').querySelector('[data-action="close"]').focus();
}
function closeModal(){if($('modal').open)$('modal').close();}
$('modal').addEventListener('close',()=>{if(opener&&document.contains(opener))opener.focus({preventScroll:true});});
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function source(key){if(!C.sources[key])return;if(!state.read.includes(key))state.read.push(key);save();render(false);showModal(C.sources[key].title,sourceBody(key));}
function challenge(i){
  if(i===2){go(9);return;}
  const body=i===0?`<p>${C.scope.question}</p><div class="options">${C.scope.options.map((x,n)=>choice('scope-select',n,x,state.scope===n)).join('')}</div>`:`<p><strong>Ejemplo didáctico ficticio.</strong> Clasifica el tipo de afirmación; no son resultados de las lecturas.</p>${C.classifications.map((x,n)=>`<label class="classification"><span><span class="card-number">${n+1}.</span>${x.text}</span><select data-group="classify" data-key="${n}" aria-label="Clasificar ejemplo ${n+1}"><option value="">Elegir…</option>${[['fact','Registro observado'],['interpretation','Interpretación posible'],['unsupported','Conclusión no sostenida']].map(([v,l])=>`<option value="${v}" ${state.classify[n]===v?'selected':''}>${l}</option>`).join('')}</select></label>`).join('')}`;
  showModal('Candado de '+seals[i],`<span class="pill">Práctica de análisis · ${status(state.seals[i])}</span><div style="margin-top:20px">${body}</div><div class="actions">${action('check-lock','Abrir el candado',`data-seal="${i}"`)}<button class="text-button" data-action="hint" data-seal="${i}">Pedir una pista</button><button class="text-button" data-action="assist" data-seal="${i}">Resolver con el facilitador</button></div>${fb('lock'+i)}<p class="note">El desafío revela una pauta. Las lecturas y el recorrido siguen disponibles.</p>`);
}
const rewardBodies=[
 '<p>Una conclusión precisa hace visible su alcance.</p><ul class="reward-list"><li>¿De qué resultado estamos hablando?</li><li>¿Qué participantes y contextos se estudiaron?</li><li>¿La frase dice «puede», «en promedio» o promete «siempre»?</li></ul><p class="note">Usa estas preguntas para revisar una promesa educativa antes de llevarla al aula.</p>',
 '<p>Ordena la lectura en tres niveles.</p><ul class="reward-list"><li><strong>Registro:</strong> qué observamos o medimos.</li><li><strong>Interpretación:</strong> qué podría explicar ese registro.</li><li><strong>Límite:</strong> qué no podemos concluir todavía.</li></ul><p class="note">Reconocer alternativas vuelve el argumento más preciso.</p>',
 '<p>El hilo de la defensa se convierte en una decisión.</p><ul class="reward-list"><li>Formula una afirmación acotada.</li><li>Sostenla con una evidencia pertinente.</li><li>Reconoce un límite o explicación alternativa.</li><li>Propón una acción y qué observarás para revisarla.</li></ul><p class="note">La secuencia ayuda a conversar. La calidad del argumento se revisa con el facilitador.</p>'
];
function reward(i){if(state.seals[i]==='pending'){challenge(i);return;}showModal('Sello de '+seals[i],`<span class="pill">${status(state.seals[i])}</span><div style="margin-top:20px">${rewardBodies[i]}</div>`);}
function unlock(i,kind='solved'){state.seals[i]=kind;save();render(false);toast('Sello de '+seals[i]+' abierto. Una pauta queda disponible.');reward(i);}
function checkLock(i){
  const right=i===0?state.scope===C.scope.correct:i===1?C.classifications.every((x,n)=>state.classify[n]===x.answer):JSON.stringify(state.order)===JSON.stringify(C.argumentSteps.map(x=>x.id));
  if(right){delete feedback['lock'+i];unlock(i);return;}
  const text=[
    'Revisa el alcance. «Cada estudiante» promete más que una tendencia media; «ninguna sirve» también generaliza más allá de una experiencia.',
    'El número de entregas es un registro. «Podría» propone una explicación; atribuir todo el aprendizaje a una pauta requiere evidencia adicional.',
    'Define primero qué sostienes. Después busca con qué sostenerlo, reconoce lo que queda abierto y termina con una decisión que puedas revisar.'
  ][i];
  feedback['lock'+i]={text,kind:'error'};
  if(i===2){render(false);$('stage').focus({preventScroll:true});}else challenge(i);
}
function hint(i){state.hints[i]++;save();const hints=[
  ['Busca una afirmación que admita variación entre experiencias.','Distingue «evidencia media favorable» de «garantía para cada persona».'],
  ['¿La frase registra, propone o asegura una causa única?','Una cantidad observada, una posibilidad y una atribución total son tres tipos de afirmación distintos.'],
  ['Empieza por lo que quieres sostener y termina por lo que vas a hacer.','Entre la afirmación y la decisión necesitas evidencia y reconocer un límite.']
  ];feedback['lock'+i]={text:`<strong>Pista ${Math.min(2,state.hints[i])}.</strong> ${hints[i][Math.min(1,state.hints[i]-1)]}`,kind:'hint'};if(i===2)render(false);else challenge(i);}
function notebook(){showModal('Tu bitácora del debate',`<p>Conserva las ideas del equipo y trasládalas a la bitácora del proyecto.</p>${Object.keys(fieldNames).map(id=>field(id,2)).join('')}<div class="actions">${action('download','Preparar mi registro')}${action('review','Abrir pauta de argumentación','',true)}</div><p class="note">${storageOK?'Tus textos se guardan en este navegador.':'El almacenamiento está restringido; copia o descarga tu registro.'} No se envían automáticamente al facilitador.</p>`);}
function exportText(){return ['BUSCADORES DE LA GAMIFICACIÓN PERDIDA','El Claro del Debate · Sesión 4 · Misión secundaria 2','Fecha: '+new Date().toLocaleDateString('es-CL'),'','POSTURAS DEL EQUIPO EN ESTE NAVEGADOR',...C.statements.flatMap((s,n)=>[`${n+1}. ${s.claim}`,'Antes: '+voteLabel(state.before[s.id]),'Después: '+voteLabel(state.after[s.id]),'']),'SELLOS DE PRÁCTICA',...seals.map((s,i)=>`${s}: ${status(state.seals[i])} · pistas consultadas: ${state.hints[i]}`),'','CIERRE NARRATIVO','Fragmento I: '+(state.fragment?'Revelado en esta sesión':'Por revelar'),'Este cierre no actualiza el Libro de Stats ni acredita la calidad de los argumentos.','',...Object.entries(fieldNames).flatMap(([id,label])=>[label.toUpperCase(),state.fields[id]||'(Sin registro)','']),'FUENTES',...Object.values(C.sources).map(s=>s.citation)].join('\n');}
function download(){
  if(exportUrl)URL.revokeObjectURL(exportUrl);
  const text=exportText();exportUrl=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));
  showModal('Tu registro está listo',`<p>Guarda las posturas y los argumentos del equipo.</p><div class="actions"><a class="button" href="${exportUrl}" download="Bitacora_El_Claro_del_Debate.txt">Descargar archivo TXT</a></div><label class="field" for="export-text" style="margin-top:24px">También puedes seleccionar y copiar el registro<textarea id="export-text" rows="10" readonly>${esc(text)}</textarea></label><p class="note">Si el marco restringe descargas, abre la misión en una pestaña o copia el texto.</p>`);
}
function fragmentInfo(){showModal('Fragmento I · Bosque de los Conceptos',`<div class="fragment-dialog">${orbSVG()}<p>El primer fragmento del Orbe del Saber vuelve a iluminar Ludaria.</p><p>Dejamos el bosque con conceptos más precisos, experiencias analizadas y argumentos abiertos a revisión.</p><p class="note">Cierre narrativo registrado en esta misión. El facilitador gestiona el cierre del módulo y los Códigos del Saber del sistema existente.</p><div class="actions">${action('close','Volver al claro','',true)}</div></div>`);}
function focusVote(id,phase,value){document.querySelector(`[data-action="vote"][data-statement="${id}"][data-phase="${phase}"][data-option="${value}"]`)?.focus({preventScroll:true});}
function handle(name,el){
  const i=Number(el.dataset.seal);
  switch(name){
    case 'begin':go(1);break;
    case 'go':go(Number(el.dataset.page));break;
    case 'close':closeModal();break;
    case 'map':showModal('Los pasos del claro',`<p>Explora cualquier pantalla. Las lecturas y los contenidos permanecen disponibles.</p><div class="modal-grid">${titles.map((t,n)=>`<button class="map-item ${state.page===n?'current':''}" data-action="go" data-page="${n}"><span>${String(n+1).padStart(2,'0')}</span>${t}</button>`).join('')}</div><div class="actions"><button class="text-button" data-action="guide">Guía para facilitar la misión</button><button class="text-button" data-action="sources">Las fuentes del claro</button><button class="text-button" data-action="reset-ask">Reiniciar esta misión</button></div>`);break;
    case 'guide':showModal('Acompañar El Claro del Debate',`<p>Sesión 4: segunda misión secundaria del Bosque de los Conceptos y cierre del módulo 1. Objetivo: contrastar mitos y evidencia sobre gamificación.</p><ul class="complete-list"><li>Pantallas 1–3: encargo y primeras posturas.</li><li>Pantalla 4: lectura de tres síntesis.</li><li>Pantallas 5–8: contraste y segunda postura.</li><li>Pantallas 9–10: debate y práctica de argumentación.</li><li>Pantallas 11–12: síntesis, formulario externo y Fragmento I.</li></ul><p>Distribución sugerida: ${minutes.join(', ')} minutos; total 90 minutos sincrónicos.</p><p>Facilita equipos que presentan, otros que preguntan y una revisión final. Las posturas abiertas no se califican automáticamente. Los tres candados revelan ayudas; la apertura acompañada queda registrada como tal.</p><p class="note">La aplicación no agrega votos de otros dispositivos, no envía respuestas y no actualiza el Libro de Stats. El formulario y los códigos reales se gestionan en los recursos existentes.</p>`);break;
    case 'vote':{const {statement:id,phase}=el.dataset,value=el.dataset.option;if(!['before','after'].includes(phase)||!C.statements.some(x=>x.id===id))return;if(phase==='before'&&state.revealed.includes(id))return;state[phase][id]=value;save();render(false);focusVote(id,phase,value);break;}
    case 'reveal':{const id=el.dataset.statement;if(!state.revealed.includes(id))state.revealed.push(id);save();render(false);document.querySelector('.round-after .choice')?.focus({preventScroll:true});toast('La lectura está abierta. Decide qué sostienes y cómo lo justificarás.');break;}
    case 'source':source(el.dataset.source);break;
    case 'metrics':showModal('Tres resultados, tres preguntas',`<p>Una conducta observable, una percepción motivacional y un resultado cognitivo responden a preguntas diferentes.</p>${metricTable()}<div class="actions"><a class="button secondary" href="${C.sources.sailer.url}" target="_blank" rel="noopener noreferrer">Consultar el metaanálisis</a></div>`);break;
    case 'sources':showModal('Las fuentes del claro',`<p>Síntesis didácticas de investigaciones citadas en la tesis. Las preguntas y desafíos son actividades propias de esta misión.</p>${Object.entries(C.sources).map(([k,s])=>`<h3>${s.short}</h3><p>${s.citation}</p><p><a href="${s.url}" target="_blank" rel="noopener noreferrer">Consultar publicación</a></p>`).join('')}<p class="note">Diseño: equipo GamiAula. Ilustraciones originales creadas para Ludaria. Los ejemplos ficticios están identificados como tales.</p>`);break;
    case 'challenge':challenge(i);break;
    case 'scope-select':state.scope=Number(el.dataset.option);delete feedback.lock0;save();challenge(0);$('modal-body').querySelector(`[data-action="scope-select"][data-option="${state.scope}"]`)?.focus({preventScroll:true});break;
    case 'check-lock':checkLock(i);break;
    case 'hint':hint(i);break;
    case 'reward':reward(i);break;
    case 'seal-info':reward(i);break;
    case 'assist':showModal('Una apertura acompañada',`<p>Conversa el desafío con el facilitador. Puedes revelar la pauta con apoyo; el sello se registrará como «Apertura acompañada».</p><div class="actions">${action('assist-confirm','Abrir con acompañamiento',`data-seal="${i}"`)}${action('challenge','Volver a intentar',`data-seal="${i}"`,true)}</div>`);break;
    case 'assist-confirm':unlock(i,'assisted');break;
    case 'order-add':{const id=el.dataset.option;if(!state.order.includes(id)){state.order.push(id);delete feedback.lock2;save();render(false);(document.querySelector('[data-action="order-add"]:not(:disabled)')||document.querySelector('[data-action="check-lock"][data-seal="2"]'))?.focus({preventScroll:true});}break;}
    case 'order-undo':state.order.pop();delete feedback.lock2;save();render(false);document.querySelector('[data-action="order-undo"]')?.focus({preventScroll:true});break;
    case 'order-reset':state.order=[];delete feedback.lock2;save();render(false);document.querySelector('[data-action="order-add"]')?.focus({preventScroll:true});break;
    case 'timer-toggle':state.timer.running=!state.timer.running;save();render(false);document.querySelector('[data-action="timer-toggle"]')?.focus({preventScroll:true});break;
    case 'timer-reset':state.timer={left:600,running:false};save();render(false);break;
    case 'review':showModal('Una pauta para revisar el argumento','<p>Lee el registro con otro equipo. Pregunten y ajusten; no necesitan coincidir en todo.</p><ul class="reward-list"><li>¿La afirmación es concreta y evita promesas absolutas?</li><li>¿La evidencia corresponde a esa afirmación?</li><li>¿Se distingue un registro de una interpretación?</li><li>¿Se reconoce un límite o una explicación alternativa?</li><li>¿La decisión para el aula dice qué observar para revisarla?</li></ul><p class="note">Esta pauta orienta una revisión humana. Cambiar de voto, escribir más o incluir palabras clave no demuestra por sí solo la calidad del argumento.</p><div class="actions">'+action('notebook','Volver a la bitácora','',true)+'</div>');break;
    case 'notebook':notebook();break;
    case 'download':download();break;
    case 'save-closing':state.closingRecorded=true;save();render(false);toast('Reflexión guardada. Prepárala para la puesta en común.');break;
    case 'fragment-ask':showModal('El cierre del Bosque de los Conceptos','<p>Después de compartir los argumentos y realizar la síntesis con Théol, revela el primer fragmento del Orbe del Saber.</p><p class="note">Es el cierre narrativo del módulo. Los sellos locales no acreditan por sí solos aprendizaje ni sustituyen el formulario de cierre.</p><div class="actions">'+action('fragment-reveal','Revelar el Fragmento I')+action('close','Volver a la síntesis','',true)+'</div>');break;
    case 'fragment-reveal':state.fragment=true;save();render(false);fragmentInfo();break;
    case 'fragment-info':fragmentInfo();break;
    case 'fullscreen':if(!document.fullscreenElement){document.documentElement.requestFullscreen?.().catch(()=>toast('Usa la opción de pantalla completa del navegador o del marco.'));}else document.exitFullscreen?.();break;
    case 'reset-ask':showModal('Volver al inicio','<p>Se borrarán las posturas, los textos, los sellos y el cierre de esta misión en este navegador. Antes puedes guardar el registro.</p><div class="actions">'+action('download','Preparar mi registro','',true)+action('reset-confirm','Reiniciar esta misión')+'</div>');break;
    case 'reset-confirm':state=defaults();feedback={};try{localStorage.removeItem(KEY);}catch(e){}closeModal();go(0);toast('El claro está listo para una nueva exploración.');break;
  }
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)handle(el.dataset.action,el);});
document.addEventListener('change',e=>{const {group,key}=e.target.dataset;if(group==='classify'){state.classify[key]=e.target.value;save();}if(group==='statement'){state.chosenStatement=e.target.value;save();const s=C.statements.find(x=>x.id===state.chosenStatement);const p=document.querySelector('.selected-claim');if(p&&s)p.textContent=s.claim;}});
document.addEventListener('input',e=>{if(e.target.dataset.field){state.fields[e.target.dataset.field]=e.target.value;save();}});
$('previous').addEventListener('click',()=>go(state.page-1));$('next').addEventListener('click',()=>go(state.page+1));
document.addEventListener('keydown',e=>{if($('modal').open||e.target.closest('input,textarea,select,button,a'))return;if(e.key==='ArrowRight'){e.preventDefault();go(state.page+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(state.page-1);}});
setInterval(()=>{if(state.timer.running&&state.timer.left>0){state.timer.left--;const timer=$('timer');if(timer)timer.textContent=timerText();if(state.timer.left%15===0)save();if(state.timer.left===0){state.timer.running=false;save();if(state.page===8)render(false);toast('Terminó el tiempo orientativo. Puedes continuar la conversación.');}}},1000);
window.addEventListener('beforeunload',save);
for(let n=0;n<12;n++){const f=document.createElement('i');f.className='fly';f.style.cssText=`left:${13+n*7}%;top:${20+(n*17)%68}%;animation-delay:${-n*1.2}s;animation-duration:${8+(n%4)*3}s`;$('fireflies').appendChild(f);}
const hash=location.hash.match(/^#pantalla-(\d+)$/);if(hash&&+hash[1]>=1&&+hash[1]<=titles.length)state.page=+hash[1]-1;
if(!state.visited.includes(state.page))state.visited.push(state.page);render();save();if(!storageOK)toast('Puedes explorar el claro; copia o descarga tu registro para conservarlo.');
})();
