const assert = require('node:assert/strict');
const fs = require('node:fs');
const crypto = require('node:crypto');
const {context,setSource} = require('./mock.cjs');
setSource(fs.readFileSync(__dirname+'/Code-Ludaria-Conectado.gs','utf8'));
const t=context();
const send=request=>{t.c.request=request;return t.run('ludariaApi(request)');};
const id=()=>crypto.randomUUID();
assert.equal(send({action:'cargar'}).ok,false);
assert.equal(t.run('prepararConexionLudaria().ok'),true);
const secret=t.props.get('LUDARIA_PIN_PEPPER');
const signup={action:'registrar',requestId:id(),data:{name:'Nicolás del Bosque',class:'Kira'}};
const account=send(signup); assert.equal(account.ok,true,account.message);
assert.match(account.key,/^LUD(?:-[A-F0-9]{6}){4}$/);
assert.equal(account.profile.skills.maestria,1);
assert.equal(account.profile.points,0);
const duplicate=send(signup);assert.equal(duplicate.profile.id,account.profile.id);assert.equal(duplicate.key,account.key);
assert.equal(send({...signup,requestId:id()}).ok,false);
assert.equal(t.sheets.get('Personajes').data.length,2);
assert.equal(JSON.stringify(t.sheets.get('Personajes').data).includes(account.key),false);
const auth=send({action:'entrar',data:{name:'  NICOLAS   DEL BOSQUE ',key:account.key.toLowerCase()}});
assert.equal(auth.ok,true,auth.message);assert.equal(auth.profile.id,account.profile.id);
assert.equal(send({action:'entrar',data:{name:signup.data.name,key:'LUD-000000-000000-000000-000000'}}).ok,false);
assert.equal(send({action:'cargar',access:auth.access+'x'}).ok,false);
let profile=auth;
function call(action,data={},requestId=id(),revision=profile.revision){const response=send({action,data,requestId,access:auth.access,expectedRevision:revision});if(response.ok&&response.profile)profile=response;return response;}
const quantities={sabiduria:0,maestria:4,creacion:0,evaluacion:0,camaraderia:0};
assert.equal(call('compra',{quantities}).ok,false);
assert.equal(call('ventaja',{id:'ojo_artesano'}).ok,false);
const runeId=id(),oldRevision=profile.revision;
const rune=call('runa',{code:'AXR314'},runeId);assert.equal(rune.ok,true,rune.message);assert.equal(profile.profile.points,5);assert.equal(profile.profile.xp,60);
assert.equal(call('runa',{code:'AXR314'},runeId,oldRevision).ok,true);
assert.equal(call('runa',{code:'AXR314'}).ok,false);
assert.equal(call('runa',{code:'ECO101'},runeId).ok,false);
assert.equal(profile.profile.points,5);
assert.equal(call('compra',{quantities},id(),oldRevision).ok,false);
const buyId=id(),buyRevision=profile.revision;
assert.equal(call('compra',{quantities},buyId).ok,true);
assert.equal(profile.profile.skills.maestria,5);assert.equal(profile.profile.points,1);
assert.equal(call('compra',{quantities},buyId,buyRevision).ok,true);assert.equal(profile.profile.points,1);
assert.equal(call('ventaja',{id:'ojo_artesano'}).ok,true);
assert.equal(call('compra',{quantities:{...quantities,maestria:1.5}}).ok,false);
assert.equal(call('compra',{quantities:{...quantities,maestria:-1}}).ok,false);
assert.equal(call('redistribuir',{skills:{sabiduria:10,maestria:10,creacion:10,evaluacion:10,camaraderia:10}}).ok,false);
assert.equal(call('redistribuir',{skills:{sabiduria:1,maestria:1,creacion:1,evaluacion:1,camaraderia:1}}).ok,true);
assert.equal(profile.profile.points,5);assert.equal(profile.profile.xp,60);assert.equal(profile.profile.skills.maestria,1);
assert.equal(call('ventaja',{id:'ojo_artesano'}).ok,false);
assert.ok(profile.profile.history.some(h=>h.type==='compra'));
assert.ok(profile.profile.history.some(h=>h.type==='redistribuir'));
assert.equal(call('cargarMision',{mission:'vetas-diseno'}).snapshot,null);
const saveId=id(),snapshot={cards:Array(18).fill(''),note:'Mi reflexión',page:2};
const saveRequest={action:'guardarMision',data:{mission:'vetas-diseno',snapshot},requestId:saveId,access:auth.access,expectedRevision:null};
assert.equal(send(saveRequest).ok,true);
assert.equal(send(saveRequest).ok,true);
assert.equal(t.sheets.get('Aventuras').data.filter(r=>r[5]==='BORRADOR').length,1);
assert.equal(send({...saveRequest,requestId:id()}).ok,false);
assert.equal(send({...saveRequest,data:{...saveRequest.data,snapshot:{note:'Otro'}},expectedRevision:saveId,requestId:id()}).ok,true);
assert.equal(call('cargarMision',{mission:'vetas-diseno'}).snapshot.note,'Otro');
assert.equal(call('cargarMision',{mission:'mision-0'}).ok,false);
const other=send({action:'registrar',requestId:id(),data:{name:'Otro explorador',class:'Kael'}});
assert.equal(send({action:'cargarMision',access:other.access,data:{mission:'vetas-diseno'}}).snapshot,null);
assert.equal(t.run('prepararConexionLudaria().ok'),true);assert.equal(t.props.get('LUDARIA_PIN_PEPPER'),secret);
assert.equal(t.sheets.get('Personajes').data.length,3);
const original=t.c.Session.getActiveUser;t.c.Session.getActiveUser=()=>({getEmail:()=>''});
assert.throws(()=>t.run('prepararConexionLudaria()'),/propietaria/);t.c.Session.getActiveUser=original;
assert.equal(t.run('doGet({parameter:{mision:"forja",entrada:"mochi"}}).html').includes('window.FORJA_ENTRY=true'),true);
assert.equal(t.run('doGet({parameter:{mision:"../secret"}}).html').includes('todavía'),true);
console.log('PASS: claves, alta repetible, alias, sesión firmada, saldos, revisión, duplicados, redistribución, ventaja actual, cuaderno por persona, conflictos, privacidad y administrador protegido.');
